### ISSUE TITLE
Change name that appears in pavucontrol ?

### ISSUE THREAD

**Issue by stuaxo** [bastibe/PySoundCard#48]
I've got an audio reactive python programme (1), and a python script that plays some audio (2), they all show up in pavucontrol as ALSA Plug-in [python]  is there any way to change the [python] bit ?

Maybe by default this could show the script name instead of [python] ?

I've been trying to make videos of the window of (1) with audio, but it's been a bit of a nightmare so far.

**Comment by stuaxo** [comment]
Managed to solve this problem by specifying the loopback device + implementing the fuzzy matching thing, so not a priority ... might be a nice feature though.

**Comment by mgeier** [comment]
I'm not familiar with pavucontrol, but how can PySoundCard influence what's displayed there?

How does it even know it has anything to do with [python]?

How is a non-Python application using PortAudio (e.g. Audacity) displayed?

**Comment by stuaxo** [comment]
I opened audacity and started recording ... then pavucontrol and the 'recording' tab, it looks like

```ALSA plug-in [audacity]```  this might be the 'client name', - I did some browsing and it looks like it is in jack and alsa, I haven't found anything mentioning it in portaudio yet though.

I guess [python] is just the executable name.

**Comment by mgeier** [comment]
I suppose it's the process name rather than the executable name, then (but I guess they are often equal)?

I don't see a sane way how PySoundCard could change that, but probably you can try one of those work-arounds (I didn't test this, though!):

* create a symbolic link to your Python executable and use this instead of `python` to start your script/application.
* try to change the process name from within Python (see, e.g., https://code.google.com/p/py-setproctitle/ or https://code.google.com/p/procname/)

Does one of those work for you?

**Comment by stuaxo** [comment]
setproctitle and setprocname didn't work... the symlink thing also didn't change things, I guess it's coming from somewhere else.

**Comment by mgeier** [comment]
OK, thanks for checking this out.

I'm out of ideas now ...

**Comment by stuaxo** [comment]
Cool, well I managed to fix my issue a different way, if I find a way to do this I'll update this, otherwise we could close this for now?
