### ISSUE TITLE
pip install on win32 - no such file or directory win/portaudio.dll

### ISSUE THREAD

**Issue by stuaxo** [bastibe/PySoundCard#52]
Hi,
   Just tried installing in a Windows 7 32 bit VM with pip and got this:

```
Running PySoundCard-0.5.0\setup.py -q bdist_egg --dist-dir c:\users\ieuser\appdata\local\temp\easy_install-ob3v2d\PySoundCard-0.5.0\egg-dist-tmp-3qsd62
error: [Errno 2] No such file or directory: 'win/portaudio32.dll'
```

**Comment by bastibe** [comment]
Yes, the pip install does not install portaudio. Please use either the Windows installer, or install portaudio manually.

**Comment by mgeier** [comment]
Alternatively, you can try the [sounddevice module](http://python-sounddevice.readthedocs.org/) which installs its own DLLs with:

   pip install sounddevice --user

**Comment by stuaxo** [comment]
Cheers - I've already ported the code from pyaudio to pysoundcard not keen to port again.

Would building python wheels that include the DLL be an acceptable solution ?

**Comment by stuaxo** [comment]
Alternately maybe pysoundcard could depend on sounddevice ?

**Comment by bastibe** [comment]
PySoundCard and SoundDevice are extremely similar. In many ways, SoundDevice is the logical continuation of PySoundCards development. If you're lucky, porting from PySoundCard to SoundDevice is as simple as changing the import.

**Comment by stuaxo** [comment]
Ah, OK .. didn't realise this ... so is  pysoundcard still around, is it evolving into something else ?

**Comment by stuaxo** [comment]
It died when I tried to install it on windows :/  https://github.com/spatialaudio/python-sounddevice/issues/7  python on windows is such a pain, but I have friends stuck in that OS  :/

**Comment by bastibe** [comment]
So, the deal is: I don't have all that much time to do open source development these days, and my friendly co-maintainer @mgeier got tired of waiting for me to look over his pull requests, so he decided to do his own thing instead. SoundDevice is the continuation of PySoundCard in all but name, and while I'm sad that I won't be part of that development, I am sure that @mgeier takes good care of the project.

PySoundCard will still be around. I won't delete it or anything. But for continued development, I would urge you to check out SoundDevice. The thing is, there is no end to the issues with PySoundCard, because the underlying C library portaudio is just kind of buggy, and we have to work around many of its problems in our code. I wish there was a better alternative than portaudio, but I don't know any.

**Comment by stuaxo** [comment]
Cheers for the info and thanks for pyaudio and pysoundcard - they have been great over the years and its great SoundDevice is carrying on.  

Loads of open source projects don't have much developer time available, I'd imagine it's probably the same in portaudio too.
